/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIFeedbackCard: typeof import('./src/components/home/AIFeedbackCard.vue')['default']
    AudioPlayer: typeof import('./src/components/listening/AudioPlayer.vue')['default']
    CustomNumericKeypad: typeof import('./src/components/auth/CustomNumericKeypad.vue')['default']
    CustomOtpInput: typeof import('./src/components/auth/CustomOtpInput.vue')['default']
    EvaluationSlide: typeof import('./src/components/onboarding/EvaluationSlide.vue')['default']
    FillInBlankQuestion: typeof import('./src/components/listening/FillInBlankQuestion.vue')['default']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    MultipleChoiceQuestion: typeof import('./src/components/listening/MultipleChoiceQuestion.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    PartIndicator: typeof import('./src/components/listening/PartIndicator.vue')['default']
    PartNavigation: typeof import('./src/components/listening/PartNavigation.vue')['default']
    PassageQuestionsTab: typeof import('./src/components/reading/PassageQuestionsTab.vue')['default']
    PrimaryButton: typeof import('./src/components/common/PrimaryButton.vue')['default']
    ProgressChart: typeof import('./src/components/home/ProgressChart.vue')['default']
    ProgressOverviewCard: typeof import('./src/components/home/ProgressOverviewCard.vue')['default']
    ProgressSlide: typeof import('./src/components/onboarding/ProgressSlide.vue')['default']
    QuestionsList: typeof import('./src/components/listening/QuestionsList.vue')['default']
    ReadingFillInBlank: typeof import('./src/components/reading/ReadingFillInBlank.vue')['default']
    ReadingMultipleChoice: typeof import('./src/components/reading/ReadingMultipleChoice.vue')['default']
    ReadingPassage: typeof import('./src/components/reading/ReadingPassage.vue')['default']
    ReadingQuestionsList: typeof import('./src/components/reading/ReadingQuestionsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillScoreCard: typeof import('./src/components/home/SkillScoreCard.vue')['default']
    SpeakingQuestionCard: typeof import('./src/components/speaking/SpeakingQuestionCard.vue')['default']
    TestNavHeader: typeof import('./src/components/common/TestNavHeader.vue')['default']
    Timer: typeof import('./src/components/listening/Timer.vue')['default']
    TimeRangeSelector: typeof import('./src/components/home/TimeRangeSelector.vue')['default']
    TrueFalseQuestion: typeof import('./src/components/listening/TrueFalseQuestion.vue')['default']
    UserHeader: typeof import('./src/components/common/UserHeader.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCircle: typeof import('vant/es')['Circle']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanField: typeof import('vant/es')['Field']
    VanProgress: typeof import('vant/es')['Progress']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSlider: typeof import('vant/es')['Slider']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VoiceRecorder: typeof import('./src/components/speaking/VoiceRecorder.vue')['default']
    WelcomeSlide: typeof import('./src/components/onboarding/WelcomeSlide.vue')['default']
    WritingAnswerInput: typeof import('./src/components/writing/WritingAnswerInput.vue')['default']
    WritingTaskCard: typeof import('./src/components/writing/WritingTaskCard.vue')['default']
  }
}
